version: '3'
services:
  db:
    image: aquiladb:local
    container_name: aquiladb
    restart: always
    # ports:
      # - 5001:5001
    volumes:
      - ${HOME}/aquilax/data:/data
      - ${HOME}/aquilax/ossl:/ossl
  hub:
    image: aquilahub:local
    container_name: aquilahub
    restart: always
    # ports:
      # - 5002:5002
    volumes:
      - ${HOME}/aquilax/data:/data
      - ${HOME}/aquilax/ossl:/ossl
  ax:
    image: aquilax:local
    container_name: aquilax
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ${HOME}/aquilax/ossl:/ossl
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${HOME}/aquilax/nginx:/etc/nginx
      - ${HOME}/aquilax/webpage/src:/usr/share/nginx/html
    ports:
      - 80:80
