version: '3'
services:
  db:
    image: aquiladb:local
    container_name: aquiladb
    restart: always
    # ports:
      # - 5001:5001
    volumes:
      - ${HOME}/aquilax/data:/data
      - ${HOME}/aquilax/ossl:/ossl
  hub:
    image: aquilahub:local
    container_name: aquilahub
    restart: always
    # ports:
      # - 5002:5002
    volumes:
      - ${HOME}/aquilax/data:/data
      - ${HOME}/aquilax/ossl:/ossl
  ax:
    image: aquilax:local
    container_name: aquilax
    restart: always
    # ports:
      # - 5003:5003
    volumes:
      - ${HOME}/aquilax/data:/data
      - ${HOME}/aquilax/ossl:/ossl
  mercury:
    image: mercury:local
    container_name: mercury
    restart: always
    # ports:
    #   - 5009:5009
  txtpick:
    image: txtpick:local
    container_name: txtpick
    restart: always
    # ports:
    #   - 5008:5008
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${HOME}/aquilax/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${HOME}/aquilax/webpage/src:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
